version: '3.9'

services:
  api:
    ports:
    - "8000:8000"
    build:
      context: .
      dockerfile: ./deploy/Dockerfile
      target: dev
    image: sowonpass-backend:latest
    volumes:
    - .:/app/
    environment:
      SOWONPASS_BACKEND_RELOAD: "True"

  db:
    ports:
    - '3306:3306'

  migrator:
    image: sowonpass-backend:latest
