version: '3.9'

services:
  api:
    build:
      context: .
      dockerfile: ./deploy/Dockerfile
      target: prod
    image: ghcr.io/gbswhs/sowonpass-backend:latest
    restart: always
    ports:
    - '8000:8000'
    networks:
    - sowonpass_backend
    env_file:
    - .env
    environment:
      SOWONPASS_BACKEND_HOST: 0.0.0.0
      SOWONPASS_BACKEND_DB_HOST: sowonpass_backend-db
      SOWONPASS_BACKEND_DB_PORT: 3306
    depends_on:
      migrator:
        condition: service_completed_successfully

  db:
    image: bitnami/mariadb:10.11
    hostname: sowonpass_backend-db
    restart: always
    expose:
    - 3306
    networks:
    - sowonpass_backend
    env_file:
    - .env
    volumes:
    - sowonpass_backend-db-data:/bitnami/mysql/data
    healthcheck:
      test: mysqladmin ping -u${SOWONPASS_BACKEND_DB_USER} -p${SOWONPASS_BACKEND_DB_PASS}
      interval: 10s
      timeout: 5s
      retries: 5

  migrator:
    image: ghcr.io/gbswhs/sowonpass-backend:latest
    restart: "no"
    entrypoint: /python3 -m alembic upgrade head
    networks:
    - sowonpass_backend
    env_file:
    - .env
    depends_on:
      adminer:
        condition: service_started

  adminer:
    image: adminer
    restart: always
    ports:
    - '8080:8080'
    networks:
    - sowonpass_backend
    depends_on:
      db:
        condition: service_healthy


networks:
  sowonpass_backend:


volumes:
  sowonpass_backend-db-data:
    name: sowonpass_backend-db-data
