version: '3.9'

services:
  api:
    build:
      context: .
      dockerfile: ./deploy/Dockerfile
    image: ghcr.io/gbswhs/sowonpass-backend:latest
    restart: always
    ports:
    - '8000:8000'
    networks:
    - sowonpass
    env_file:
    - .env
    environment:
      SOWONPASS_BACKEND_HOST: 0.0.0.0
      SOWONPASS_BACKEND_DB_HOST: sowonpass_backend-db
      SOWONPASS_BACKEND_DB_PORT: 3306
    depends_on:
      db:
        condition: service_started

  db:
    image: bitnami/mariadb:10.11
    hostname: sowonpass_backend-db
    restart: always
    expose:
    - 3306
    networks:
    - sowonpass
    env_file:
    - .env
    volumes:
    - sowonpass_backend-db-data:/bitnami/mysql/data

  migrator:
    build:
      context: .
      dockerfile: ./deploy/Dockerfile
    image: ghcr.io/gbswhs/sowonpass-backend:latest
    restart: "no"
    entrypoint: python3 -m alembic upgrade head
    networks:
    - sowonpass
    env_file:
    - .env
    depends_on:
      db:
        condition: service_started

  adminer:
    image: adminer
    restart: always
    ports:
    - '8080:8080'
    networks:
    - sowonpass
    depends_on:
      db:
        condition: service_started


networks:
  sowonpass:


volumes:
  sowonpass_backend-db-data:
    name: sowonpass_backend-db-data
