version: '3.9'

services:
  api:
    ports:
    - "8000:8000"
    build:
      context: .
      dockerfile: ./deploy/Dockerfile
      target: dev
    image: sowonpass_backend:${SOWONPASS_BACKEND_VERSION:-latest}
    volumes:
    - .:/app/
    environment:
      SOWONPASS_BACKEND_RELOAD: "True"
    depends_on:
      migrator:
        condition: service_completed_successfully

  migrator:
    build:
      context: .
      dockerfile: ./deploy/Dockerfile
      target: dev
    image: sowonpass_backend:${SOWONPASS_BACKEND_VERSION:-latest}
    entrypoint: alembic upgrade head
    depends_on:
      db:
        condition: service_healthy
